### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by odan** [rfussien/dotenv#1]
## Detailed description

On my local machine parse_ini_string with file_get_contents is up to 50% faster then parse_ini_file.

```php
$env = parse_ini_string(file_get_contents('.env'));
```
vs.
```php
$env = parse_ini_file('.env');
```
## Context

The parser.

## Possible implementation

https://github.com/rfussien/dotenv/blob/master/src/Parser.php#L53

```php
$this->content = parse_ini_string(file_get_contents($file), false, $this->scannerMode);
```
## Your environment

* Version used: PHP 7.1
* Operating system and version: Windows 7

**Comment by rfussien** [comment]
Hi,
I couldn't see any gain, nether any loss with 7.0, but if you say it's better with 7.1... (_cf 74611811d71c7f6b610e1660dd2dad8bf3ca2154_)
